### ISSUE TITLE
Unable to Publish Listing after Inputting Stripe's information

### ISSUE THREAD

**Issue by hggz** [sharetribe/flex-template-web#1087] opened 2019-05-10 03:30 UTC
**Describe the bug** A clear and concise description of what the bug is.

I'm unable to proceed after inputting all of the stripe connect information after making a listing. I get an error saying 'Whoops try again'.

**To Reproduce** Steps to reproduce the behavior:
1) Clone repo
2) do quick start steps
3) create account
4) attempt to create listing
5) Note, in the payment screen I added various debug payment options from stripe connect's testing docs, but none of them worked.

**Expected behavior** A clear and concise description of what you expected to happen.

The listing gets created.

**Desktop (please complete the following information):**

- OS: [OSX]
- Browser [safari]
- Version [12.1]

**Comment by OtterleyW** [comment] 2019-05-13 07:19
Hello there,

with this kind of issues, I would recommend contacting directly our support team by emailing to help@sharetribe.com or using the chat widget in Console.

With this information, we are not able to reproduce the issue. Could you check the following things: 
* Have you added your Stripe secret key to your Console? This is required for the payments to work.
* Could you check which version of Stripe API your account is using?  Our setup is for API version '2019-02-19' and later. If you have an older API version in use, you need to update your Stripe API. You can check your Stripe API version from Stripe Dashboard -> Developers.

If these steps don't solve the problem, please check the error message from your browser's developer console. That should provide more information.

**Comment by Gnito** [comment] 2019-05-16 11:28
I'm closing this issue for now - since I assume that the issue was about Console not having Stripe's secret key. 

(Stripe's publishable key is for the client-app/frontend calls and the secret key should be saved to Console so that API can talk to Stripe too.)

**Closed by Gnito** 2019-05-16 11:28 UTC
