### ISSUE TITLE
Sharetribe-scripts

### ISSUE THREAD

**Issue by suecom** [sharetribe/flex-template-web#1041] opened 2019-03-05 18:59 UTC
You need to include sharetribe-scripts for the current documentation to work (package.json)

**Comment by Gnito** [comment] 2019-03-08 18:43
Could you elaborate more? I didn’t catch the issue yet.

And sorry for slow reaction on our side. We have been submerged to issues related to recent Stripe API change.

**Comment by suecom** [comment] 2019-03-08 18:59
I created a clean environment and just followed the docs. Two packages: inquirer and Sharetribe-scripts weren’t installed. So, devDependancies weren’t installed????

I npm installed them (before realising I should be using yarn) and all was well. I’ve not managed to get yarn test to run successfully despite installing lots more packages.

I’m still familiarising myself with this project. I guess you’ve a few global packages in your build environment?

Allister
allister@oldencars.com
07729 175634

**Comment by Gnito** [comment] 2019-03-08 19:55
There should not be any - and this is the first time we have got feedback about dependencies not being installed.

What happens if you try to echo environment variable `NODE_ENV`? If it’s printing ”production”, that will cause issues like this.

Or alternatively you could enforce yarn to install dev-depencies with `yarn install --production=false`

**Comment by suecom** [comment] 2019-03-08 21:17
If your new users follows your document (yarn install, yarn run config), they will get an error due to ‘inquirer’ not being installed because it’s only included in the devDependancies. sharetribe-scripts wasn’t installed either?

Obviously on my clean VM, NODE_ENV wasn't set in the shells environment, so I can’t remember why these weren’t installed by default, but of course I know I can set —production=false to make them; I am (very) familiar with this build environment (although I’ve never bothered with yarn).

The only clue might be I had installed the latest release of node before I started? ‘yarn install’ failed on requiring 10.4, so I downgraded to the latest LTS (10.15.3?) and updated the package.json to accept it. ‘yarn install’ then ran, but yarn run config then failed with no inquirer?

This really isn’t important (for me); just a pain for someone following your docs if they’re not familiar with npm package management (then again, they should be if they’re bothering to download FTW!).

You should probably change the node dependancy to “>=10.4”? We find 11.x far more performant than the 10.X release (on our production sites), and it uses less memory. At least accept 10.15.3 :-)

Allister
allister@oldencars.com
07729 175634

**Comment by Gnito** [comment] 2019-03-11 14:47
Yeah, that engine setup in `package.json` has caused quite many problems and we have actually discussed of removing it. Thank you for raising this issue up again. 

There have been some problems with different Node.js versions (I think the latest was with 10.13), but having a fixed version is a bigger problem since most people are facing it. 

So, I removed that engine section from package.json in the latest master and introduced a small troubleshooting section to [How to deploy FTW to production document](https://www.sharetribe.com/docs/guides/how-to-deploy-ftw-to-production/#troubleshooting-heroku)

**Comment by Gnito** [comment] 2019-03-12 12:33
I'll close this Issue now. As stated above, engine setup is removed from the latest master and if there are more issues - it's better to open new tickets and include steps on how to reproduce the issue.

**Closed by Gnito** 2019-03-12 12:33 UTC

**Comment by dylman123** [comment] 2021-03-31 05:06
Hi Sharetribe,

I was searching for an appropriate place to raise this question and found this rather old thread.

In the nodeJS module `sharetribe-scripts` the file `scripts/build.js` contains the following (lines 11-13):

```
// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'production'
process.env.NODE_ENV = 'production'
```

Pretty sure this means that these env vars are baked in at build time. 

#### The challenge
I am trying to containerize my nodeJS app (which is based on the FTW daily template). In order to do so, I require env vars be set at runtime. This is so the same pre-built Docker image can be deployed in any environment (dev vs staging vs prod). I’m finding that even with setting env vars such as `NODE_ENV = development` at runtime, it's too late. My built image ignores the runtime env var uses `production` anyway.

I am also a paying customer of Sharetribe Flex and wish to deploy with containers. Now I am wondering - is containerization supported? 

Can the env vars be parameterized in the build scripts? This would make for a more flexible architecture.
